### ISSUE TITLE
About entity name

### ISSUE THREAD

**Issue by Cranooooooo** [MIRALab-USTC/QE-ConE#2]
Nice work, thanks for sharing the code.
By the way, I wonder where can I find the names of all entities in the dataset?
Currently, I can only get the entity indices w/o semantic meanings.

Thanks

**Comment by zq0x7a0x71** [comment]
Thanks for your interest in our work.  To get semantic meanings of entities, you can
1. Read entity ids from `id2ent.pkl`.
2. Follow [this repo](https://github.com/villmow/datasets_knowledge_embedding) to get textual information of entities based on their ids.

Hope it helps.

**Comment by Cranooooooo** [comment]
> Thanks for your interest in our work.  To get semantic meanings of entities, you can
> 
> 1. Read entity ids from `id2ent.pkl`.
> 
> 2. Follow [this repo](https://github.com/villmow/datasets_knowledge_embedding) to get textual information of entities based on their ids.
> 
> 
> 
> Hope it helps.

Thx! That's really helpful~
